baseURL: 'https://sagarchamling.com/'
title: Sagar Chamling's Blogging Site
paginate: 5
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: true
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
disqusShortname: sagarchamling
googleAnalytics: G-DKKQ68YLLJ

minify:
  disableXML: true
  minifyOutput: true

languages:
  en:
    languageName: 'English'
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production # To enable google analytics, opengraph, twitter-cards and schema.
  description: 'Explore insightful blog posts and discover content based on a wide range of emerging technologies, programming, networking, and cybersecurity.'
  keywords:
    [
      Portfolio,
      Site,
      Blog,
      Blogging,
      Technology,
      Cybersecurity,
      Networking,
      Programming,
      Software,
      Engineering,
      DevOps,
      DevSecOps,
      Sagar,
      Chamling,
      Sagar Chamling,
      Presentation,
      Training,
      Software Development,
      Cloud Computing,
      Cloud Security,
      Ethical Hacking,
      Penetration Testing,
    ]
  author: 'Sagar Chamling'
  defaultTheme: auto
  disableThemeToggle: false
  showDate: true
  showDateUpdated: true
  showHeadingAnchors: true
  showPagination: true
  showReadingTime: true
  showTableOfContents: true
  showTaxonomies: false
  showWordCount: true
  showSummary: true
  sharingLinks: true
  ShowShareButtons: true
  ShowReadingTime: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: false
  ShowToc: true
  images: ['logo.svg']
  comments: true

  profileMode:
    enabled: false
    title: ðŸ‘‹, I'm Sagar Chamling,
    imageUrl: 'img/profile.jpg'
    imageTitle: Sagar Chamling's Photo
    imageWidth: 250
    imageHeight: 250
    subtitle: 'A passionate full-stack software engineer and cyber security enthusiast. Explore my recent blog articles, where I write about my works, share valuable insights on emerging technologies, programming, networking and cybersecurity in a company accepted best practices and standards. Stay tuned for more!.'
    buttons:
      - name: Archives
        url: archives
      - name: Tags
        url: tags
      - name: '#tech'
        url: blogs/tech

  homeInfoParams:
    enabled: true
    imageUrl: 'img/profile.jpg'
    imageTitle: Sagar Chamling's Photo
    imageWidth: 250
    imageHeight: 250
    buttons:
      - name: Archives
        url: archives
      - name: Tags
        url: tags
      - name: '#tech'
        url: blogs/tech

  socialIcons:
    - name: github
      url: 'https://github.com/cham11ng'
    - name: twitter
      url: 'https://twitter.com/cham11ng'
    - name: linkedin
      url: 'https://linkedin.com/in/cham11ng'
    - name: stackoverflow
      url: 'https://stackoverflow.com/users/5056594/sagar-chamling'
    - name: youtube
      url: 'https://www.youtube.com/@SagarChamling'
    - name: buymeacoffee
      url: 'https://www.buymeacoffee.com/cham11ng'

  editPost:
    URL: 'https://github.com/cham11ng/sagarchamling.com/tree/main/content'
    Text: 'Suggest Changes'
    appendFilePath: true

  label:
    text: "cham11ng's blog"
    # icon: "logo.png"
    # iconHeight: 35

  # analytics:
  # google:
  # SiteVerificationTag: "abc"

  assets:
    favicon: 'favicon.ico'
    favicon16x16: 'img/favicon-16x16.png'
    favicon32x32: 'img/favicon-32x32.png'
    apple_touch_icon: 'img/apple-touch-icon.png'
    safari_pinned_tab: 'safari-pinned-tab.svg'
    android_chrome192x192: 'img/android-chrome-192x192.png'
    android_chrome512x512: 'img/android-chrome-512x512.png'

  # cover:
  #     hidden: true # hide everywhere but not in structured data
  #     hiddenInList: true # hide on list pages and home
  #     hiddenInSingle: true # hide on single page

  # fuseOpts:
  #     isCaseSensitive: false
  #     shouldSort: true
  #     location: 0
  #     distance: 1000
  #     threshold: 0.4
  #     minMatchCharLength: 0
  #     limit: 10 # refer: https://www.fusejs.io/api/methods.html#search
  #     keys: ["title", "permalink", "summary", "content"]

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai

privacy:
  vimeo:
    disabled: false
    simple: true

  twitter:
    disabled: false
    enableDNT: true
    simple: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
